name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |
          T
          2,READ(A)
          T
          5,WRITE(A)
        expected-output: '1'
        comparison-method: exact
        timeout: 10
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          3,READ(A)
          5,WRITE(A)
          T
          1,READ(B)
          8,WRITE(B)
        expected-output: '1'
        comparison-method: exact
        timeout: 10
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |
          T
          2,READ(A)
          3,WRITE(A)
          17,READ(B)
          19,WRITE(B)
          T
          7,WRITE(A)
          9,WRITE(B)
        expected-output: '0'
        comparison-method: exact
        timeout: 10
    - name: Test 4
      id: test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 4
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          2,READ(A)
          4,WRITE(B)
          T
          1,READ(A)
          3,READ(B)
          5,WRITE(B)
          11,WRITE(C)
          T
          4,READ(C)
          7,WRITE(C)
        expected-output: '0'
        comparison-method: exact
        timeout: 10
    - name: Test 5
      id: test-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 5
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          2,READ(A)
          4,WRITE(B)
          T
          1,READ(A)
          3,READ(C)
          5,WRITE(C)
          T
          4,READ(D)
          7,WRITE(D)
          19,READ(E)
        expected-output: '1'
        comparison-method: exact
        timeout: 10
    - name: Test 6
      id: test-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 6
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          7,READ(A)
          11,WRITE(A)
          T
          3,READ(B)
          8,WRITE(B)
          11,WRITE(C)
          T
          4,READ(C)
          7,WRITE(C)
        expected-output: '1'
        comparison-method: exact
        timeout: 10
    - name: Test 7
      id: test-7
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 7
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          7,READ(A)
          11,WRITE(A)
          T
          3,READ(B)
          8,WRITE(B)
          T
          4,READ(C)
          9,WRITE(C)
          T
          6,READ(D)
          10,WRITE(D)
          T
          5,READ(E)
          12,WRITE(E)
        expected-output: '1'
        comparison-method: exact
        timeout: 10
    - name: Test 8
      id: test-8
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 8
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          2,READ(A)
          6,WRITE(A)
          T
          3,READ(B)
          7,WRITE(B)
          T
          4,READ(C)
          9,WRITE(C)
          T
          5,WRITE(A)
          T
          8,READ(D)
          10,WRITE(D)
          T
          11,READ(C)
          12,WRITE(C)
        expected-output: '0'
        comparison-method: exact
        timeout: 10
    - name: Test 9
      id: test-9
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 9
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          18,READ(A)
          22,READ(B)
          23,READ(C)
          25,WRITE(D)
          30,WRITE(A)
          T
          4,READ(B)
          5,READ(C)
          9,WRITE(D)
          10,READ(E)
          11,READ(F)
          12,READ(G)
          13,READ(H)
          14,WRITE(D)
          T
          7,READ(A)
          12,READ(C)
          15,READ(E)
          18,READ(F)
          19,READ(H)
          23,READ(B)
          28,WRITE(A)
        expected-output: '0'
        comparison-method: exact
        timeout: 10
    - name: Test 10
      id: test-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 10
        setup-command: "./setup.sh"
        command: "./run.sh"
        input: |-
          T
          18,READ(A)
          22,READ(B)
          23,READ(C)
          25,WRITE(D)
          30,WRITE(A)
          T
          4,READ(B)
          5,READ(C)
          9,WRITE(D)
          10,READ(E)
          11,READ(F)
          12,READ(G)
          13,READ(H)
          14,WRITE(D)
          T
          7,READ(A)
          10,READ(B)
          12,READ(C)
          15,READ(E)
          18,READ(F)
          19,READ(H)
          28,WRITE(H)
        expected-output: '1'
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
        TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
        TEST-6_RESULTS: "${{steps.test-6.outputs.result}}"
        TEST-7_RESULTS: "${{steps.test-7.outputs.result}}"
        TEST-8_RESULTS: "${{steps.test-8.outputs.result}}"
        TEST-9_RESULTS: "${{steps.test-9.outputs.result}}"
        TEST-10_RESULTS: "${{steps.test-10.outputs.result}}"
      with:
        runners: test-1,test-2,test-3,test-4,test-5,test-6,test-7,test-8,test-9,test-10
